name: Build Windows Kernel Driver

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4

    - name: Download EWDK (Takes 5-10 mins)
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2196230" -OutFile ewdk.iso

    - name: Build Driver using EWDK
      run: |
        $mountResult = Mount-DiskImage -ImagePath ewdk.iso -PassThru
        $driveLetter = ($mountResult | Get-Volume).DriveLetter
        cmd.exe /c "${driveLetter}:\BuildEnv\SetupBuildEnv.cmd && msbuild rbxdriver.sln /p:Configuration=Release /p:Platform=x64"
        Dismount-DiskImage -ImagePath ewdk.iso
      
    - name: Upload Driver Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rbxdrv-release
        path: x64/Release/
