name: Build Windows Kernel Driver

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Driver (rbxdriver)
      run: |
        msbuild rbxdriver.sln /p:Configuration=Release /p:Platform=x64
      
    - name: Upload Driver Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rbxdrv.sys
        path: x64/Release/rbxdrv.sys
